# Generated by Django 4.2.3 on 2025-11-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority_score',
            field=models.FloatField(null=True),
        ),
    ]
