# Generated by Django 4.2.3 on 2025-11-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_priority_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
